#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=23:00:00   # walltime
#SBATCH --ntasks=1   # number of processes (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1G   # memory per CPU core
#SBATCH -J "GIFT-Aug-02-02"   # job name
#SBATCH --mail-user=williamunger@u.boisestate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=outAug02-02.txt


../../bin/giftCycle -e -f -k ../Input/key128Aug02-02.txt -t ../Input/plain32Aug02-02.txt
