#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=8:00:00   # walltime
#SBATCH --ntasks=1   # number of processes (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1G   # memory per CPU core
#SBATCH -J "GIFT-July-9-01"   # job name
#SBATCH --mail-user=williamunger@u.boisestate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL


../../bin/giftCycle -e -f -k ../Input/key128.txt -t ../Input/plainJuly9-01.txt
