#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=8:00:00   # walltime
#SBATCH --ntasks=1   # number of processes (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1G   # memory per CPU core
#SBATCH -J "GIFT-July-15-04"   # job name
#SBATCH --mail-user=williamunger@u.boisestate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=outJuly15-04.txt


../../bin/giftCycle -e -f -k ../Input/key128.txt -t ../Input/plainJuly15-04.txt
